language: ruby
bundler_args: --without production
before_script: RAILS_ENV=test bundle exec rake db:setup
script: RAILS_ENV=test bundle exec rspec

services:
  - elasticsearch
  - postgresql

# for elasticsearch
before_script:
  - sleep 10
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake elasticsearch:create_indexes
